services:
  - type: web
    name: telegram-media-bot
    env: python
    buildCommand: ""
    startCommand: ./start.sh
    envVars:
      - key: BOT_TOKEN
        value: your-telegram-bot-token
      - key: MONGODB_URI
        value: your-mongodb-uri
